---
abstract: 'Include a module and its dependencies in inc/'
author:
  - 'Leon Timmermans <leont@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Path::Class: 0
  Test::DZil: 0
  Test::More: 0.88
  strict: 0
  warnings: 0
configure_requires:
  Module::Build::Tiny: 0.025
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Role-ModuleIncluder
no_index:
  directory:
    - corpus
requires:
  Dist::Zilla::File::InMemory: 0
  Dist::Zilla::Role::FileGatherer: 0
  Dist::Zilla::Role::FileInjector: 0
  File::Slurp: 0
  List::MoreUtils: 0
  Module::CoreList: 0
  Module::Metadata: 0
  Moose: 0
  Moose::Role: 0
  MooseX::Types::Perl: 0
  Perl::PrereqScanner: 0
  Scalar::Util: 0
  namespace::autoclean: 0
  perl: 5.006
  version: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Dist-Zilla-Role-ModuleIncluder
  repository: git://github.com/Leont/dist-zilla-role-moduleincluder.git
version: 0.003
